### ISSUE TITLE
Get Column Count does not return number of columns due to XLRDError

### ISSUE THREAD

**Issue by dxtr80** [zero88/robotframework-excel#19]
Get Column Count doesn't work as expected and return XLRDError: No sheet named <b'AC_25_1150_PTP'>
Good to mention that file is opened and Get Sheet Names return in my case proper names of sheets like: 
@{Sh_names} = [ AC_25_1150_PTP \| AC_25_1150_GTG \| AC_25_1000_PTP \| AC 25_800_PTP \| ACC_20_1150 ]

**Environment**
- robotframework  7.1.1
- robotframework-excel   1.0.0b4
- xlrd    2.0.1
- xlwt    1.3.0
- Python 3.13.0 64bit
- Win10 64 22h2

**To Reproduce**
1. Open any Excel (xls) file with couple of sheets inside
2. Use Get Sheet Names to get sheet names   
3. Use Get Column Count to get number of sheets inside

**Exception Log**
 3. XLRDError: No sheet named <b'AC_25_1150_PTP'>

**Expected behavior**
3. Get Column Count should report "4" sheets in my case

**Additional context**

**Comment by zero88** [comment]
Thank you for reporting.
I will find a time this week to reproduce the issue and fix it, if possible.

**Comment by dxtr80** [comment]
Hi @zero88 any chance to fix this? Only this is blocking my script after I moved to Python 3.

**Comment by zero88** [comment]
Hi @dxtr80 , I cannot reproduce it by both xlrd@1.2.0 and xlrd@2.0.1 on python 3.11.

Could you pls try to replace [this excel file](https://github.com/zero88/robotframework-excel/blob/224868095cf7f45ec9d0c5bc65da057db4d44733/tests/data/ExcelRobotTest.xls) by yours, then run robot by [this suite](https://github.com/zero88/robotframework-excel/blob/224868095cf7f45ec9d0c5bc65da057db4d44733/tests/acceptance/ExcelRobotTest.robot)

```bash
robot -L DEBUG -d out/uat -v type:xls ./tests/acceptance
```
Paste/attach robot log if it fails. 

Is it possible to stick with `xlrd@1.2.0`?

Honestly, I haven't maintained this library for a long time, so the dependencies are outdated. I'm trying to re-set it up and adding GitHub Actions to make life is easier

**Comment by dxtr80** [comment]
Hi @zero88, that was my fault. I needed to upgrade my code using e.g. Encode String To Bytes which was working well in Python2 and now not working in my code as expected, So after change this particular line no issues observed, like described above with **Get Column Count**. I downgraded xlrd@1.2.0. Additional I will switch to xlxs as well this time :)
